# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anurag Kapur
email: anurag@beancrunch.com
description: > # this means to ignore newlines until "baseurl:"
  CTO @Zzish; ex-@Zzish, @BCG, @FT, @NewsUKTech, @SapientIndia; ğŸš£â€â™€ï¸ @TheLeaRC ex-@ChChBc; ğŸ‘¨â€ğŸ“@GGSIPUOfficial, @UniofOxford
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.anuragkapur.com" # the base hostname & protocol for your site
twitter_username: anuragkapur
github_username:  anuragkapur

# Build settings
markdown: kramdown
